language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t yanggwangseong/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true yanggwangseong/react-test-app npm run test

after_success:
  - docker build -t yanggwangseong/docker-frontend2 ./frontend
  - docker build -t yanggwangseong/docker-backend2 ./backend
  - docker build -t yanggwangseong/docker-nginx2 ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push yanggwangseong/docker-frontend2
  - docker push yanggwangseong/docker-backend2
  - docker push yanggwangseong/docker-nginx2

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "Dockerfullstackapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-586840563682"
  bucket_path: "docker-fullstack-app"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY